// examples/vue/src/views/examples/vc/TreeVCExample/TreeSingle.vue
<script setup lang="ts">
import { ref } from 'vue'

import { WppTree } from '@platform-ui-kit/components-library-vue'

import { data } from './config'

const treeData = ref(data)

const handleTreeChange = (event: CustomEvent) => {
  console.log('handleTreeChange event :>> ', event.detail)

  treeData.value = event.detail.treeState
}

const handleActionClick = (event: CustomEvent) => {
  console.log('handleActionClick', event.detail)
}
</script>

<template>
  <div data-testid="single-tree-container">
    <h3 class="title">Single tree</h3>
    <WppTree
      class="tree"
      :data="treeData"
      @wppChange="handleTreeChange"
      @wppActionClick="handleActionClick"
      data-testid="single-tree"
    />
  </div>
</template>

// examples/angular/src/app/pages/vc/trees/components/tree-single/tree-single.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { data } from '../../config'

@Component({
  selector: 'app-single-tree-example',
  templateUrl: './tree-single.html',
  styleUrls: ['./tree-single.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeSingle {
  public treeData = data

  public handleTreeChange = (event: Event) => {
    console.log('handleTreeChange event :>> ', (event as CustomEvent).detail)

    this.treeData = (event as CustomEvent).detail.treeState
  }

  public handleActionClick = (event: Event) => {
    console.log('handleActionClick', (event as CustomEvent).detail)
  }
}
