// examples/react/src/pages/vc/Inputs/components/DecimalInput.tsx
import React, { useRef, useState } from 'react'
import { InputChangeEventDetail } from '@platform-ui-kit/components-library'
import { WppInput } from '@platform-ui-kit/components-library-react'
import { WppInputCustomEvent } from '@platform-ui-kit/components-library/dist/types/components'

interface IProps {
  size: 'm' | 's'
  labelText: string
  className?: string
}

const DecimalInput = ({ size, className, labelText }: IProps) => {
  const [inputValues, setInputValues] = useState<string | undefined>(undefined)
  const inputRef = useRef<null | HTMLWppInputElement>(null)

  const validateLength = (event: WppInputCustomEvent<InputChangeEventDetail>) => {
    const inputValue = event.detail.value

    setInputValues(inputValue)
  }

  return (
    <>
      <WppInput
        ref={inputRef}
        labelConfig={{
          text: labelText,
        }}
        required
        name={'wpp-decimal-input-1'}
        className={className}
        type="decimal"
        size={size}
        data-testid="boundaries-values-input"
        onWppChange={validateLength}
        value={inputValues}
        minLength={3}
        maxLength={8}
        placeholder="12,23"
      />
    </>
  )
}

export default DecimalInput

// examples/vue/src/views/examples/vc/InputVCExample/components/DecimalInput.vue
<script lang="ts">
import { defineComponent, ref } from 'vue'

import { WppInput } from '@platform-ui-kit/components-library-vue'
import type { WppInputCustomEvent } from '@platform-ui-kit/components-library/dist/types/components'
import type { InputChangeEventDetail } from '@platform-ui-kit/components-library'

// const inputValues = ref<string | undefined>(undefined)
export default defineComponent({
  components: {
    WppInput: WppInput,
  },
  data() {
    return {
      size: 'm' as string,
      labelText:
        'Decimal Input with minimum and maximum length validations. Default error messages. Value must be between [3, 8] to be valid.' as string,
      className: '' as string,
      inputValues: '' as string | undefined,
    }
  },
  methods: {
    validateLength(event: WppInputCustomEvent<InputChangeEventDetail>) {
      this.inputValues = event.detail.value
    },
  },
})
</script>

<template>
  <div>
    <WppInput
      :labelConfig="{
        text: this.labelText,
      }"
      required
      :className="className"
      type="decimal"
      :size="size"
      data-testid="boundaries-values-input"
      @wppChange="validateLength"
      :value="inputValues"
      minLength="3"
      maxLength="8"
      placeholder="12,23"
    />
  </div>
</template>

<style scoped></style>
