// examples/vue/src/views/examples/TopBarExample/TopBarExample.vue
<script setup lang="ts">
import { ref } from "vue";

import {
  WppTopbar,
  WppButton,
  WppTypography,
} from "@platform-ui-kit/components-library-vue";

const initNavigation = [
  {
    label: "Home",
    value: "home",
    path: "/topbar",
  },
  {
    label: "Client services",
    value: "clientServices",
    path: "/topbar/client-services",
  },
  {
    label: "Learning",
    value: "learning",
    children: [
      {
        label: "Guided tour",
        value: "guidedTour",
        path: "/topbar/learning/guided-tour",
      },
      {
        label: "Case studies",
        value: "caseStudies",
        path: "/topbar/learning/case-studies",
      },
      {
        label: "Community",
        value: "community",
        path: "/topbar/learning/community",
      },
    ],
  },
  {
    label: "Marketplace",
    value: "marketplace",
    path: "/topbar/marketplace",
  },
  {
    label: "Dev portal",
    value: "devPortal",
    path: "/topbar/devPortal",
  },
];

const firstValue = ref("devPortal");
const secondValue = ref("community");
const navigationData = ref(initNavigation);

const handleTopbarItemChange = (event: CustomEvent) => {
  firstValue.value = event.detail.value;
  secondValue.value = event.detail.value;

  console.log(event.detail.path);
};

const handleAddNavigationItemToBeginning = () => {
  navigationData.value = [
    { label: "Start", value: "start", path: "/topbar/start" },
    ...navigationData.value,
  ];
};

const handleAddNavigationItemToEnd = () => {
  navigationData.value = [
    ...navigationData.value,
    { label: "End", value: "end", path: "/topbar/end" },
  ];
};
</script>

<template>
  <div>
    <div class="page">
      <WppTopbar
        :value="firstValue"
        :navigation="navigationData"
        @wppChange="handleTopbarItemChange"
      >
        <div slot="app" class="app">
          <img
            src="https://easydrawingguides.com/wp-content/uploads/2018/09/Impossible-Triangle-09.png"
            class="image"
          />
          <WppTypography class="name" type="m-strong" tag="h3">
            APP Name
          </WppTypography>
        </div>
      </WppTopbar>

      <WppTopbar :value="firstValue" :navigation="navigationData" />

      <WppTopbar :value="secondValue" :navigation="navigationData" />

      <div class="actions">
        <WppButton
          variant="secondary"
          @click="handleAddNavigationItemToBeginning"
        >
          Add new navigation to beginning
        </WppButton>
        <WppButton variant="secondary" @click="handleAddNavigationItemToEnd">
          Add new navigation to end
        </WppButton>
      </div>
    </div>
  </div>
</template>

<style scoped>
.page {
  padding: 20px 0 50px;
  box-shadow: 0 4px 12px rgb(52 58 63 / 10.2%);
}

.image {
  display: flex;
  width: 40px;
  max-width: 40px;
  height: 40px;
  margin-right: 12px;
}

.app {
  display: flex;
  align-items: center;
  margin-right: 32px;
}

.name {
  white-space: nowrap;
}

.actions {
  display: inline-flex;
  flex-direction: column;
  justify-content: space-between;
  height: 100px;
  margin-top: 20px;
}
</style>

// examples/react/src/pages/vc/MenuContextBasedComponents/TopbarExample.tsx
import React, { useEffect, useState } from 'react'

import { WppTopbarItem, WppTopbar, WppTypography } from '@platform-ui-kit/components-library-react'
import { NavigationState } from '@platform-ui-kit/components-library'
import styles from './TopbarExample.module.scss'

const initNavigation: NavigationState[] = [
  {
    label: 'Home',
    value: 'home',
    path: '/topbar',
  },
  {
    label: 'Client services',
    value: 'clientServices',
    path: '/topbar/client-services',
  },
  {
    label: 'Learning',
    value: 'learning',
    children: [
      {
        label: 'Guided tour',
        value: 'guidedTour',
        path: '/topbar/learning/guided-tour',
      },
      {
        label: 'Case studies',
        value: 'caseStudies',
        path: '/topbar/learning/case-studies',
      },
      {
        label: 'Community',
        value: 'community',
        path: '/topbar/learning/community',
      },
    ],
  },
  {
    label: 'Marketplace',
    value: 'marketplace',
    path: '/topbar/marketplace',
  },
  {
    label: 'Dev portal',
    value: 'devPortal',
    path: '/topbar/devPortal',
  },
]

const children: NavigationState[] = [
  {
    label: 'Guided tour',
    value: 'guidedTour',
    path: '/topbar/learning/guided-tour',
  },
  {
    label: 'Case studies',
    value: 'caseStudies',
    path: '/topbar/learning/case-studies',
  },
  {
    label: 'Community',
    value: 'community',
    path: '/topbar/learning/community',
  },
]

const getNavigationContent = (children: NavigationState[] = [], label = 'Learning'): NavigationState => ({
  label,
  value: label,
  children,
})

export const TopbarExample = () => {
  const [path, navigate] = useState('')
  const [navigation, setNavigate] = useState<NavigationState>(getNavigationContent(children.slice(0, 1)))

  useEffect(() => {
    setTimeout(() => {
      setNavigate(getNavigationContent(children.slice(0, 2)))
    }, 1000)

    setTimeout(() => {
      setNavigate(getNavigationContent(children, 'Updated learning'))
    }, 2000)

    setTimeout(() => {
      setNavigate(getNavigationContent(children.slice(0, 1)))
    }, 4000)
  }, [])

  const handleTopbarItemChange = (event: CustomEvent) => {
    navigate(event.detail.value)
  }

  return (
    <>
      <h3>Topbar Item example</h3>
      <WppTopbarItem
        firstLevel
        navigation={navigation as NavigationState}
        active={true}
        activeItems={['selectedNavItemValue']}
        onWppActiveTopbarItemChange={() => console.log('click wpp active topbar item')}
      />

      <h3>Topbar example</h3>
      <WppTypography>Selected value: {path}</WppTypography>
      <WppTopbar value={path} navigation={initNavigation} onWppChange={handleTopbarItemChange}>
        <div slot="app" className={styles.app}>
          <img
            src="https://easydrawingguides.com/wp-content/uploads/2018/09/Impossible-Triangle-09.png"
            className={styles.image}
          />
          <WppTypography className={styles.name} type="m-strong" tag="h3">
            APP Name
          </WppTypography>
        </div>
      </WppTopbar>
    </>
  )
}
