// examples/react/src/pages/vc/Selects/Examples/CustomDropdown.tsx
import React, { useRef, useState } from 'react'

import { WppInput, WppIconChevron, WppPopover, WppListItem } from '@platform-ui-kit/components-library-react'

const OPTIONS_LIST = ['Admin', 'Country Admin', 'User']

const CustomDropdown = () => {
  const [selectedOption, setSelectedOption] = useState<string>('')
  const [isActive, setIsActive] = useState<boolean>(false)
  const popoverRef = useRef<HTMLWppPopoverElement>(null)

  const handleOptionSelect = (selectedOption: string) => {
    setSelectedOption(selectedOption)
    popoverRef.current?.closePopover()
  }

  const style: Record<string, string> = { '--wpp-list-item-width': '200px' }

  return (
    <WppPopover
      ref={popoverRef}
      config={{
        onShow: () => setIsActive(true),
        onHide: () => setIsActive(false),
        triggerElementWidth: true,
      }}
    >
      <WppInput
        value={selectedOption}
        slot="trigger-element"
        placeholder="Select user role"
        labelConfig={{ text: 'Role (Custom dropdown using WppInput + WppPoppover)' }}
        required
      >
        <WppIconChevron slot="icon-end" direction={isActive ? 'up' : 'down'} />
      </WppInput>
      <div style={style}>
        {/* Any other content here */}
        {OPTIONS_LIST.map(option => (
          <WppListItem
            key={option}
            checked={selectedOption === option}
            onWppChangeListItem={() => handleOptionSelect(option)}
          >
            <p slot="label">{option}</p>
          </WppListItem>
        ))}
      </div>
    </WppPopover>
  )
}

export default CustomDropdown

// examples/vue/src/views/examples/SelectsExample/Examples/CustomDropdown.vue
<script setup lang="ts">
import { WppInput, WppIconChevron, WppPopover, WppListItem } from '@platform-ui-kit/components-library-vue'

const OPTIONS_LIST = ['Admin', 'Country Admin', 'User']
import { ref } from 'vue'

const selectedOption = ref()
const isActive = ref<boolean>(false)
const popoverRef = ref<HTMLWppPopoverElement>()

const handleOptionSelect = (chosenOption: string) => {
  selectedOption.value = chosenOption
  popoverRef.value?.closePopover
}

const style: Record<string, string> = { '--wpp-list-item-width': '200px' }
</script>

<template>
  <WppPopover
    :ref='popoverRef'
    :config="{
    onShow: () => isActive = true,
    onHide: () => isActive = false,
    triggerElementWidth: true,
    }"
  >
    <WppInput
      :value='selectedOption'
      slot="trigger-element"
      placeholder="Select user role"
      :labelConfig="{ text: 'Role (Custom dropdown using WppInput + WppPoppover)' }"
      name="custom-input-name"
      required
    >
      <WppIconChevron slot="icon-end" :direction="isActive ? 'up' : 'down'" />
    </WppInput>
    <div :style='style'>
      <WppListItem
        v-for="option in OPTIONS_LIST"
        :key='option'
        :checked='selectedOption === option'
        @wppChangeListItem='handleOptionSelect(option)'
      >
        <p slot="label">{{ option }}</p>
      </WppListItem>
    </div>
  </WppPopover>
</template>
