// examples/react/src/pages/Search/Examples/InfiniteScrollWithLazyLoad.tsx
import React, { useEffect, useRef, useState } from 'react'
import { AutocompleteDefaultOption, LoadMoreHandler } from '@platform-ui-kit/components-library'
import { WppListItem, WppSearch } from '@platform-ui-kit/components-library-react'

import { BasicOption, generateInfiniteResults, isInfiniteLastPage } from '../../Autocomplete/options'

import styles from '../Search.module.scss'
import { ResultsView } from '../ResultsView'

export const InfiniteScrollWithLazyLoad = () => {
  const [infiniteValue, setInfiniteValue] = useState<AutocompleteDefaultOption[]>([])

  const isInfiniteFirstLoadSkipped = useRef(false)
  const infiniteLoadMoreTimer = useRef<ReturnType<typeof setTimeout>>()
  const [infiniteSearchPage, setInfiniteSearchPage] = useState(0)
  const [isSearchingInfinite, setIsSearchingInfinite] = useState(false)
  const [infiniteSearchValue, setInfiniteSearchValue] = useState('')
  const [infiniteSearchResults, setInfiniteSearchResults] = useState<BasicOption[]>([])

  const infiniteSearchValueTrimmed = infiniteSearchValue.trim()
  const infiniteSearchLoadMore: LoadMoreHandler = () =>
    new Promise(resolve => {
      const timeout = 300 + Math.round(Math.random() * 700)
      const page = infiniteSearchResults.length ? infiniteSearchPage + 1 : infiniteSearchPage

      infiniteLoadMoreTimer.current = setTimeout(() => {
        infiniteLoadMoreTimer.current = undefined
        setInfiniteSearchResults(current => [...current, ...generateInfiniteResults(infiniteSearchValueTrimmed, page)])
        setInfiniteSearchPage(page)

        resolve()
      }, timeout)
    })

  // Load infinite options based on search
  useEffect(() => {
    if (isInfiniteFirstLoadSkipped.current) {
      if (infiniteLoadMoreTimer.current) {
        clearTimeout(infiniteLoadMoreTimer.current)
        infiniteLoadMoreTimer.current = undefined
      }

      setIsSearchingInfinite(true)

      const timeout = 700 + Math.round(Math.random() * 1300)
      const timer = setTimeout(() => {
        setInfiniteSearchResults(() => [...generateInfiniteResults(infiniteSearchValueTrimmed, 0)])
        setInfiniteSearchPage(0)
        setIsSearchingInfinite(false)
      }, timeout)

      return () => clearTimeout(timer)
    } else {
      isInfiniteFirstLoadSkipped.current = true
    }
  }, [infiniteSearchValueTrimmed])

  return (
    <div className={styles.item}>
      <WppSearch
        required
        infinite
        infiniteLastPage={isInfiniteLastPage(infiniteSearchValueTrimmed, infiniteSearchPage)}
        loading={isSearchingInfinite}
        name="infinite-list"
        labelConfig={{ text: 'Infinite scroll with lazy load' }}
        placeholder="Scroll me"
        value={infiniteValue}
        loadMore={infiniteSearchLoadMore}
        onWppSearchValueChange={(e: CustomEvent) => setInfiniteSearchValue(e.detail)}
        onWppChange={(e: CustomEvent) => setInfiniteValue(e.detail.value as AutocompleteDefaultOption[])}
        simpleSearch
      >
        {infiniteSearchResults.map(option => (
          <WppListItem key={option.id} value={option} label={option.label}>
            <p slot="label">{option.label}</p>
          </WppListItem>
        ))}
      </WppSearch>

      <ResultsView value={infiniteValue.map(i => i.id)} />
    </div>
  )
}

// examples/vue/src/views/examples/AutocompleteExample/examples/InfiniteScrollWithLazyLoad.vue
<script lang="ts">
import { defineComponent } from "vue";
import type { AutocompleteDefaultOption } from "@platform-ui-kit/components-library";

import {
  WppAutocomplete,
  WppListItem,
} from "@platform-ui-kit/components-library-vue";

import type { LoadMoreHandler } from "@platform-ui-kit/components-library";

import SelectedValues from "../SelectedValues.vue";
import ResultsView from "../ResultsView.vue";

import type { BasicOption } from "../options";
import { isInfiniteLastPage } from "../options";
import { generateInfiniteResults } from "@platform-ui-kit/react-example/src/pages/Autocomplete/options";

let infiniteLoadMoreTimer: ReturnType<typeof setTimeout> | null = null;
let searchTimer: ReturnType<typeof setTimeout> | null = null;

export default defineComponent({
  name: "InfiniteScrollWithLazyLoad",
  components: {
    WppAutocomplete: WppAutocomplete,
    WppListItem: WppListItem,
    SelectedValues: SelectedValues,
    ResultsView: ResultsView,
  },
  data() {
    return {
      isInfiniteLastPage: isInfiniteLastPage,

      infiniteValue: [] as AutocompleteDefaultOption[],
      infiniteSearchPage: 0,
      isSearchingInfinite: false,
      infiniteSearchValue: "",
      infiniteSearchResults: [] as BasicOption[],
    };
  },
  watch: {
    infiniteSearchValue(newSearchValue, oldSearchValue) {
      if (newSearchValue.trim() === oldSearchValue.trim()) {
        return;
      }

      const infiniteSearchValueTrimmed = newSearchValue.trim();

      if (infiniteLoadMoreTimer) {
        clearTimeout(infiniteLoadMoreTimer);
        infiniteLoadMoreTimer = null;
      }

      if (searchTimer) {
        clearTimeout(searchTimer);
        searchTimer = newSearchValue;
      }

      this.isSearchingInfinite = true;

      const timeout = 700 + Math.round(Math.random() * 1300);
      searchTimer = setTimeout(() => {
        this.infiniteSearchResults = generateInfiniteResults(
          infiniteSearchValueTrimmed,
          0
        );

        this.infiniteSearchPage = 0;

        this.isSearchingInfinite = false;
      }, timeout);
    },
  },
  computed: {
    infiniteSearchLoadMore(): LoadMoreHandler {
      const infiniteSearchValueTrimmed = this.infiniteSearchValue.trim();

      const loadMore: LoadMoreHandler = () =>
        new Promise((resolve) => {
          const timeout = 300 + Math.round(Math.random() * 700);
          const page = this.infiniteSearchResults.length
            ? this.infiniteSearchPage + 1
            : this.infiniteSearchPage;

          infiniteLoadMoreTimer = setTimeout(() => {
            infiniteLoadMoreTimer = null;
            this.infiniteSearchResults = [
              ...this.infiniteSearchResults,
              ...generateInfiniteResults(infiniteSearchValueTrimmed, page),
            ];
            this.infiniteSearchPage = page;

            resolve();
          }, timeout);
        });

      return loadMore;
    },
  },
  methods: {
    handleSearchValueChange(event: CustomEvent) {
      this.infiniteSearchValue = event.detail;
    },
    handleChange(event: CustomEvent) {
      this.infiniteValue = event.detail.value;
    },
    handlePillCloseClick(removedId: number) {
      this.infiniteValue = this.infiniteValue.filter((i) => i.id !== removedId);
    },
  },
});
</script>

<template>
  <div class="item">
    <WppAutocomplete
      required
      infinite
      :infiniteLastPage="
        isInfiniteLastPage(infiniteSearchValue.trim(), infiniteSearchPage)
      "
      :loading="isSearchingInfinite"
      name="infinite-list"
      :labelConfig="{ text: 'Infinite scroll with lazy load' }"
      placeholder="Scroll me"
      :value="infiniteValue"
      :loadMore="infiniteSearchLoadMore"
      @wppSearchValueChange="handleSearchValueChange"
      @wppChange="handleChange"
      multiple
      showCreateNewElement
    >
      <WppListItem
        v-for="option in infiniteSearchResults"
        :key="option.id"
        :value="option"
        :label="option.label"
      >
        <p slot="label">{{ option.label }}</p>
      </WppListItem>
      <SelectedValues
        :values="infiniteValue"
        @closeClick="(value) => handlePillCloseClick(value)"
      />
    </WppAutocomplete>

    <ResultsView :value="infiniteValue.map((i) => i.id)" />
  </div>
</template>

<style scoped></style>
