// examples/angular/src/app/pages/vc/inputs/components/decimalInput.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { WppInputCustomEvent } from '@platform-ui-kit/components-library/dist/types/components'
import { InputChangeEventDetail } from '@platform-ui-kit/components-library'

@Component({
  selector: 'decimal-input',
  templateUrl: './decimalInput.html',
  styleUrls: ['./decimalInput.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DecimalInput {
  public value: string | null = null
  public inputValues: string = undefined
  public inputRef: HTMLWppInputElement = null

  public validateLength = (event: Event) => {
    this.inputValues = (event as WppInputCustomEvent<InputChangeEventDetail>).detail.value
  }

  public getLabelConfig = (text: string) => ({
    text,
  })
}

// examples/react/src/pages/vc/Inputs/components/DecimalInput.tsx
import React, { useRef, useState } from 'react'
import { InputChangeEventDetail } from '@platform-ui-kit/components-library'
import { WppInput } from '@platform-ui-kit/components-library-react'
import { WppInputCustomEvent } from '@platform-ui-kit/components-library/dist/types/components'

interface IProps {
  size: 'm' | 's'
  labelText: string
  className?: string
}

const DecimalInput = ({ size, className, labelText }: IProps) => {
  const [inputValues, setInputValues] = useState<string | undefined>(undefined)
  const inputRef = useRef<null | HTMLWppInputElement>(null)

  const validateLength = (event: WppInputCustomEvent<InputChangeEventDetail>) => {
    const inputValue = event.detail.value

    setInputValues(inputValue)
  }

  return (
    <>
      <WppInput
        ref={inputRef}
        labelConfig={{
          text: labelText,
        }}
        required
        name={'wpp-decimal-input-1'}
        className={className}
        type="decimal"
        size={size}
        data-testid="boundaries-values-input"
        onWppChange={validateLength}
        value={inputValues}
        minLength={3}
        maxLength={8}
        placeholder="12,23"
      />
    </>
  )
}

export default DecimalInput
