// examples/react/src/pages/Autocomplete/Examples/ServerLoadSameOptionForDifferentSearch.tsx
import React, { useState } from 'react'
import { WppAutocomplete, WppListItem } from '@platform-ui-kit/components-library-react'
import { AutocompleteDefaultOption } from '@platform-ui-kit/components-library'

import { delay } from '../../../utils'
import { SelectedValues } from '../SelectedValues'

import styles from '../Autocomplete.module.scss'

const createOptions = (optionsNumber: number): AutocompleteDefaultOption[] => [
  {
    id: 'okta',
    label: '1Cloud Okta',
  },
  ...Array(Math.min(optionsNumber, 5))
    .fill(null)
    .map((_, index) => ({
      id: `opt${index}`,
      label: `Additional Option ${index + 1}`,
    })),
]

export const ServerLoadSameOptionForDifferentSearch = () => {
  const [value, setValue] = useState<AutocompleteDefaultOption[]>([])
  const [options, setOptions] = useState<AutocompleteDefaultOption[]>([])
  const [isLoading, setIsLoading] = useState<boolean>(false)

  const handleSearchChange = async (event: CustomEvent<string>) => {
    const searchString = event.detail

    setIsLoading(true)

    await delay(1000)
    setOptions(createOptions(searchString.length))

    setIsLoading(false)
  }

  return (
    <div className={styles.item}>
      <WppAutocomplete
        required
        loading={isLoading}
        labelConfig={{ text: 'Server load same option for different search input (option - "1Cloud Okta")' }}
        placeholder='Type "1Cloud Okta"'
        value={value}
        onWppSearchValueChange={handleSearchChange}
        onWppChange={(e: CustomEvent) => setValue(e.detail.value as AutocompleteDefaultOption[])}
        multiple
        showCreateNewElement
        simpleSearch
        infinite
      >
        {options.map(option => (
          <WppListItem key={option.id} value={option} label={option.label}>
            <p slot="label">{option.label}</p>
          </WppListItem>
        ))}
        <SelectedValues
          values={value}
          onCloseClick={clickedValue => setValue(value.filter(i => i.id !== clickedValue))}
        />
      </WppAutocomplete>
    </div>
  )
}

// examples/angular/src/app/pages/autocomplete-example/components/server-load-same-option-for-different-search/server-load-same-option-for-different-search.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { AutocompleteDefaultOption } from '@platform-ui-kit/components-library'
import { delay } from '@platform-ui-kit/react-example/src/utils'

@Component({
  selector: 'app-autocomplete-same-option-for-different-search-example',
  templateUrl: './server-load-same-option-for-different-search.html',
  styleUrls: ['./autocomplete-example.page.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ServerLoadSameOptionForDifferentSearch {
  public isLoading = false
  public value: AutocompleteDefaultOption[] = []
  public options: AutocompleteDefaultOption[] = []
  public timer = null

  public createOptions = (optionsNumber: number): AutocompleteDefaultOption[] => [
    {
      id: 'okta',
      label: '1Cloud Okta',
    },
    ...Array(Math.min(optionsNumber, 5))
      .fill(null)
      .map((_, index) => ({
        id: `opt${index}`,
        label: `Additional Option ${index + 1}`,
      })),
  ]

  public handleSearchChange = async (event: Event) => {
    const searchString = (event as CustomEvent<string>).detail

    this.isLoading = true

    await delay(1000)
    this.options = this.createOptions(searchString.length)

    this.isLoading = false
  }

  public handleValueChange = async (event: Event) => {
    this.value = (event as CustomEvent).detail.value as AutocompleteDefaultOption[]
  }

  public getLabelConfig = (text: string) => ({
    text,
  })
}
