// examples/vue/src/views/examples/vc/TreeVCExample/TreeMultipleWithNotSelectableItem.vue
<script setup lang="ts">
import { ref } from "vue";

import { WppTree } from "@platform-ui-kit/components-library-vue";

const data: any[] = [
  {
    id: "0",
    title: "Cars",
    children: [
      {
        id: "0-0",
        title: "Toyota",
        iconsEnd: [
          {
            name: "remove",
            icon: "wpp-icon-info",
          },
          {
            name: "save",
            icon: "wpp-icon-cross",
          },
        ],
      },
    ],
  },
  {
    id: "1",
    title: "Planes",
    isNotSelectable: true,
    children: [
      {
        id: "1-0",
        title: "B-52",
      },
      {
        id: "1-1",
        title: "MIG-21",
      },
    ],
  },
];

const treeData = ref(data);

const handleTreeChange = (event: CustomEvent) => {
  console.log("handleTreeChange event :>> ", event.detail);

  treeData.value = event.detail.treeState;
};
</script>

<template>
  <h3 class="title">Multiple tree with not selectable Planes item</h3>

  <WppTree
    class="tree"
    :data="treeData"
    multiple
    @wppChange="handleTreeChange"
    data-testid="multiple-tree"
  />
</template>

// examples/angular/src/app/pages/vc/trees/components/tree-multiple-with-not-selectable-item/tree-multiple-with-not-selectable-item.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { data } from '../../config'

@Component({
  selector: 'app-multiple-tree-with-not-selectable-item-example',
  templateUrl: './tree-multiple-with-not-selectable-item.html',
  styleUrls: ['./tree-multiple-with-not-selectable-item.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeMultipleWithNotSelectableItem {
  public data: any[] = [
    {
      id: '0',
      title: 'Cars',
      children: [
        {
          id: '0-0',
          title: 'Toyota',
          iconsEnd: [
            {
              name: 'remove',
              icon: 'wpp-icon-info',
            },
            {
              name: 'save',
              icon: 'wpp-icon-cross',
            },
          ],
        },
      ],
    },
    {
      id: '1',
      title: 'Planes',
      isNotSelectable: true,
      children: [
        {
          id: '1-0',
          title: 'B-52',
        },
        {
          id: '1-1',
          title: 'MIG-21',
        },
      ],
    },
  ]

  public treeData = data

  public handleTreeChange = (event: Event) => {
    console.log('handleTreeChange event :>> ', (event as CustomEvent).detail)

    this.treeData = (event as CustomEvent).detail.treeState
  }
}
