// examples/vue/src/views/examples/vc/TreeVCExample/TreeEndContent.vue
<script setup lang="ts">
import { ref } from 'vue'

import { WppTree } from '@platform-ui-kit/components-library-vue'

import { dataWithEndContent } from './config'

const treeData = ref(dataWithEndContent)

const handleTreeChange = (event: CustomEvent) => {
  console.log('handleTreeChange event :>> ', event.detail)

  treeData.value = event.detail.treeState
}

const handleActionClick = (event: CustomEvent) => {
  console.log('handleActionClick', event.detail)
}
</script>

<template>
  <div data-testid="single-tree-container">
    <h3 class="title">Single tree with End Content</h3>
    <WppTree class="tree" :data="treeData" @wppChange="handleTreeChange" @wppActionClick="handleActionClick" multiple
      data-testid="single-tree-end-content" />
  </div>
</template>

// examples/angular/src/app/pages/vc/trees/components/tree-end-content/tree-end-content.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { dataWithEndContent } from '../../config'

@Component({
  selector: 'app-end-content-tree-example',
  templateUrl: './tree-end-content.html',
  styleUrls: ['./tree-end-content.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeEndContent {
  public treeData = dataWithEndContent

  public handleTreeChange = (event: Event) => {
    console.log('handleTreeChange event :>> ', (event as CustomEvent).detail)

    this.treeData = (event as CustomEvent).detail.treeState
  }

  public handleActionClick = (event: Event) => {
    console.log('handleActionClick', (event as CustomEvent).detail)
  }
}
