// examples/vue/src/views/examples/AgGridTableExample/components/HeaderCellRenderer.vue
<script lang="ts">
import { defineComponent } from "vue";

import {
  WppTypography,
  WppIconSort,
} from "@platform-ui-kit/components-library-vue";

export default defineComponent({
  components: {
    WppTypography: WppTypography,
    WppIconSort: WppIconSort,
  },
  setup(props) {
    const { displayName, enableSorting } = props.params;

    return {
      params: props.params,
      enableSorting,
      displayName,
    };
  },
  methods: {
    handleHeaderCellClick() {
      const props = this.params;
      if (!props.enableSorting) return;

      const items: ("asc" | "desc" | null)[] = ["asc", "desc", null];
      const selectedSort = props.column.getSort();
      const selectedSortIndex = selectedSort ? items.indexOf(selectedSort) : -1;
      const nextSortType =
        selectedSortIndex === -1 || selectedSortIndex === items.length - 1
          ? "asc"
          : items[selectedSortIndex + 1];

      props.setSort(nextSortType);
    },
  },
});
</script>

<template>
  <div class="ag-header-cell-comp" @click="handleHeaderCellClick">
    <WppTypography type="s-strong">{{ displayName }}</WppTypography>
    <div class="ag-sorting" v-if="enableSorting">
      <WppIconSort class="top-sort-icon" />
    </div>
  </div>
</template>

<style scoped></style>

// examples/angular/src/app/pages/ag-grid-table-example/components/header-cell-renderer/header-cell-renderer.ts
import { Component } from '@angular/core'
import { IHeaderAngularComp } from 'ag-grid-angular'
import { IHeaderParams } from 'ag-grid-community'

@Component({
  selector: 'app-ag-grid-table-header-cell-renderer',
  templateUrl: './header-cell-renderer.html',
})
export class HeaderCellRenderer implements IHeaderAngularComp {
  public params: IHeaderParams | undefined

  agInit(params: IHeaderParams): void {
    this.params = params
  }

  public handleHeaderCellClick = () => {
    if (!this.params || !this.params.enableSorting) return

    const items: ('asc' | 'desc' | null)[] = ['asc', 'desc', null]
    const selectedSort = this.params.column.getSort()
    const selectedSortIndex = selectedSort ? items.indexOf(selectedSort) : -1
    const nextSortType =
      selectedSortIndex === -1 || selectedSortIndex === items.length - 1 ? 'asc' : items[selectedSortIndex + 1]

    this.params.setSort(nextSortType)
  }

  public getColor = (isActive: boolean | undefined): string =>
    isActive ? 'var(--wpp-icon-color-active)' : 'var(--wpp-grey-color-600)'

  refresh() {
    return false
  }
}
