// examples/vue/src/views/examples/TextSelect/TextSelect.vue
<script setup>
import { ref } from 'vue'
import { WppSelect, WppTypography } from '@platform-ui-kit/components-library-vue'
import { SAMPLE_LIST_2 } from './consts'

const value = ref([])

const handleChange = event => {
  console.log('On Change single', event.detail)
  value.value = event.detail.value
}
</script>

<template>
  <div class="container">
    <div class="section">
      <WppTypography type="2xl-heading">Default Select</WppTypography>

      <div class="content">
        <WppSelect
          type="text"
          name="select-component"
          class="selectItem"
          data-testid="default-text-select-m"
          :list="SAMPLE_LIST_2"
          :label-config="{ text: 'Size M' }"
          placeholder="Choose option"
          :value="value"
          autoFocus
          @wppChange="handleChange"
        />

        <WppSelect
          type="text"
          name="select-component"
          class="selectItem"
          data-testid="default-text-select-s"
          :list="SAMPLE_LIST_2"
          :label-config="{ text: 'Size S' }"
          placeholder="Choose option"
          :value="value"
          autoFocus
          size="s"
          @wppChange="handleChange"
        />
      </div>
    </div>

    <div class="section">
      <WppTypography type="2xl-heading">Disabled Select</WppTypography>

      <div class="content">
        <WppSelect
          type="text"
          name="select-component"
          class="selectItem"
          data-testid="disabled-text-select-m"
          disabled
          :list="SAMPLE_LIST_2"
          :label-config="{ text: 'Size M' }"
          placeholder="Choose option"
          :value="value"
        />

        <WppSelect
          type="text"
          name="select-component"
          class="selectItem"
          data-testid="disabled-text-select-s"
          disabled
          :list="SAMPLE_LIST_2"
          :label-config="{ text: 'Size S' }"
          placeholder="Choose option"
          :value="value"
          size="s"
        />
      </div>
    </div>
  </div>
</template>

<style scoped>
.container {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  padding: 50px;
}

.item {
  margin-bottom: 20px;
}

.selectsContainer {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  align-items: flex-start;
  width: 900px;
  margin-top: 50px;
  padding: 10px;
  overflow: hidden;
  border: 1px solid black;
  border-radius: 20px;
}

.section {
  width: 900px;
  margin-bottom: 40px;
}

.content {
  display: flex;
  justify-content: space-between;
  margin-top: 10px;
}

.selectItem {
  width: 300px;
}

.scenarios {
  width: 900px;
}

.scenario {
  margin-top: 20px;
  margin-bottom: 60px;
}

.title {
  margin-bottom: 20px;
}

.subTitle {
  display: block;
  margin: 10px 0;
}

.truncationContainer {
  flex-direction: column;
}

.selectItem {
  margin-bottom: 20px;
}

.selectItem:last-child {
  margin-bottom: 0;
}

.selects {
  display: flex;
  justify-content: space-between;
  margin-bottom: 20px;
}

.selects .selectItem {
  width: 300px;
}

.actions {
  margin-bottom: 20px;
}

.actions .buttonItem {
  margin-right: 20px;
  margin-bottom: 10px;
}
</style>

// examples/react/src/pages/TextSelect/TextSelect.tsx
import React, { useState } from 'react'
import styles from '../SingleSelect/SingleSelect.module.scss'
import { WppSelect, WppTypography } from '@platform-ui-kit/components-library-react'
import { SelectChangeEventDetail } from '@platform-ui-kit/components-library'

import { SAMPLE_LIST_2 } from '../SingleSelect/consts'
import ChangingValue from '../SingleSelect/Examples/ChangingValue'
import DependableSelects from '../SingleSelect/Examples/DependableSelects'
import TestingTruncation from './components/TestingTruncation'
import DropdownWidth from './components/DropdownWidth'
import LoadingData from '../SingleSelect/Examples/LoadingData'
import TestingEvents from '../SingleSelect/Examples/TestingEvents'
import TestingMethods from '../SingleSelect/Examples/TestingMethods'
import { WppSelectCustomEvent } from '@platform-ui-kit/components-library/src/components'

const TextSelect = () => {
  const [value, setValue] = useState<string>('')

  return (
    <div className={styles.container}>
      <div className={styles.section}>
        <WppTypography type="2xl-heading">Default Select</WppTypography>

        <div className={styles.content}>
          <WppSelect
            type="text"
            name="select-component"
            className={styles.selectItem}
            data-testid="default-text-select-m"
            list={SAMPLE_LIST_2}
            labelConfig={{
              text: 'Default',
            }}
            placeholder={'Choose option'}
            value={value}
            autoFocus
            onWppChange={(e: WppSelectCustomEvent<SelectChangeEventDetail>) => {
              console.log('On Change text', e.detail)

              setValue(e.detail.value)
            }}
          />
        </div>
      </div>

      <div className={styles.section}>
        <WppTypography type="2xl-heading">Disabled Select</WppTypography>

        <div className={styles.content}>
          <WppSelect
            type="text"
            name="select-component"
            className={styles.selectItem}
            disabled
            data-testid="disabled-text-select-m"
            list={SAMPLE_LIST_2}
            labelConfig={{
              text: 'Disabled',
            }}
            placeholder={'Choose option'}
            value={value}
            autoFocus
            onWppChange={(e: WppSelectCustomEvent<SelectChangeEventDetail>) => {
              console.log('On Change text', e.detail)

              setValue(e.detail.value)
            }}
          />
        </div>
      </div>

      <WppTypography type="3xl-heading">Scenarios</WppTypography>

      <div className={styles.scenarios}>
        <ChangingValue type="text" />
        <DependableSelects type="text" />
        <DropdownWidth />
        <TestingTruncation />
        <LoadingData type="text" />
        <TestingEvents type="text" />
        <TestingMethods type="text" />
      </div>
    </div>
  )
}

export default TextSelect
