// examples/vue/src/views/examples/vc/TreeVCExample/TreeSingleWithDisabledAnimation.vue
<script setup lang="ts">
import { ref } from 'vue'
import { data } from './config'
import { WppTree } from '@platform-ui-kit/components-library-vue'
import type { TreeActionClickEventDetail } from '@platform-ui-kit/components-library/src'

const treeData = ref(data)

const handleTreeChange = (event: CustomEvent) => {
  console.log('handleTreeChange event :>> ', event.detail)
  treeData.value = event.detail.treeState
}

const handleActionClick = (event: CustomEvent<TreeActionClickEventDetail>) => {
  console.log('handleActionClick', event.detail)
}
</script>

<template>
  <div>
    <h3 class="title">Single tree with disabled open/close animation</h3>
    <WppTree
      class="tree"
      :data="treeData"
      @wppChange="handleTreeChange"
      data-testid="single-tree"
      @wppActionClick="handleActionClick"
      disableOpenCloseAnimation=true
    />
  </div>
</template>

// examples/angular/src/app/pages/vc/trees/components/tree-single-with-disabled-animation/tree-single-with-disabled-animation.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { TreeActionClickEventDetail } from '@platform-ui-kit/components-library'
import { data } from '../../config'

@Component({
  selector: 'app-single-tree-no-animation-example',
  templateUrl: './tree-single-with-disabled-animation.html',
  styleUrls: ['./tree-single-with-disabled-animation.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeSingleWithDisabledAnimation {
  public treeData = data

  public handleTreeChange = (event: Event) => {
    console.log('handleTreeChange event :>> ', (event as CustomEvent).detail)
    this.treeData = (event as CustomEvent).detail.treeState
  }

  public handleActionClick = (event: Event) => {
    console.log('handleActionClick', (event as CustomEvent<TreeActionClickEventDetail>).detail)
  }
}
