// examples/angular/src/app/pages/vc/selects-combined/selects-combinedVC.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { SAMPLE_LIST_COMBINED } from '../../single-select-example/consts'

@Component({
  selector: 'app-select-combined-example',
  templateUrl: './selects-combinedVC.html',
  styleUrls: ['./selects-combinedVC.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SelectsCombinedVC {
  public value: string = 'usd'
  public inputValue: string = '100'
  public LIST = SAMPLE_LIST_COMBINED

  public handleWppChange = (event: Event) => {
    const { value: newValue, inputValue: newInputValue } = (event as CustomEvent).detail

    this.value = newValue
    this.inputValue = newInputValue
    console.log('WppChange event:', newValue, newInputValue)
  }

  public getLabelConfig = (text: string) => ({
    text,
  })
}

// examples/react/src/pages/vc/SelectsCombined/SelectsCombinedVC.tsx
import { useState } from 'react'
import { WppSelect } from '@platform-ui-kit/components-library-react'
import styles from './SelectsCombinedVC.module.scss'
import { SAMPLE_LIST_COMBINED } from '../../SingleSelect/consts'

const LIST = [...SAMPLE_LIST_COMBINED]

export const SelectsCombinedVCPage = () => {
  const [value, setValue] = useState('usd')
  const [inputValue, setInputValue] = useState('100')

  const handleWppChange = (e: CustomEvent) => {
    const { value: newValue, inputValue: newInputValue } = e.detail

    setValue(newValue)
    setInputValue(newInputValue)
    console.log('WppChange event:', newValue, newInputValue)
  }

  return (
    <div className={styles.container}>
      <h1 className="title">Selects Combined</h1>

      <h3 className="subtitle">Size M</h3>
      <div className={styles.variants}>
        <WppSelect
          type="combined"
          name="combined-select"
          value={value}
          inputValue={inputValue}
          placeholder="Placeholder"
          size="m"
          disabled={false}
          required
          labelConfig={{ text: 'Currency' }}
          dropdownWidth="auto"
          onWppChange={handleWppChange}
          list={LIST}
        ></WppSelect>

        <WppSelect
          type="combined"
          name="combined-select"
          value={value}
          inputValue={inputValue}
          placeholder="Placeholder"
          size="m"
          disabled={true}
          required
          labelConfig={{ text: 'Currency' }}
          dropdownWidth="auto"
          onWppChange={handleWppChange}
          list={LIST}
        ></WppSelect>
      </div>

      <h3 className="subtitle">Size S</h3>
      <div className={styles.variants}>
        <WppSelect
          type="combined"
          name="combined-select"
          value={value}
          inputValue={inputValue}
          placeholder="Placeholder"
          size="s"
          disabled={false}
          required
          labelConfig={{ text: 'Currency' }}
          dropdownWidth="auto"
          onWppChange={handleWppChange}
          list={LIST}
        ></WppSelect>

        <WppSelect
          type="combined"
          name="combined-select"
          value={value}
          inputValue={inputValue}
          placeholder="Placeholder"
          size="s"
          disabled={true}
          required
          labelConfig={{ text: 'Currency' }}
          dropdownWidth="auto"
          onWppChange={handleWppChange}
          list={LIST}
        ></WppSelect>
      </div>
    </div>
  )
}
