// examples/vue/src/views/examples/FileUploadExample/Examples/AcceptProp.vue
<script setup lang="ts">
import { ref } from 'vue'

import { WppFileUpload } from '@platform-ui-kit/components-library-vue'
const file = ref([])

const handleFileUploadChange = (event: CustomEvent) => {
  file.value = (event.detail.value)
}
</script>

<template>
  <div class="container">
    <h3 class="text">File Upload with provided accept prop</h3>
    <pre>accept=['.png']</pre>
    <WppFileUpload
      :value="file"
      @wppChange="handleFileUploadChange"
      data-testid="file-upload-multiple"
      size="1"
      :accept="['.png']"
    />
  </div>
</template>

<style>
.text {
  margin: 20px 0;
}

.container {
  display: flex;
  flex-direction: column;
  width: 500px;
  padding-left: 10px;

  --wpp-file-upload-item-max-width: 500px;
}

.fileLoader {
  --wpp-file-upload-item-max-width: 500px;
}

.items {
  width: 500px;
  margin-right: 30px;
}
</style>

// examples/react/src/pages/FileUpload/Examples/AcceptProp.tsx
import { WppFileUpload } from '@platform-ui-kit/components-library-react'
import { useState } from 'react'

import styles from '../FileUpload.module.scss'

export const AcceptProp = () => {
  const [file, setFiles] = useState([])
  const handleFileUploadChange = (event: CustomEvent) => {
    setFiles(event.detail.value)
  }

  return (
    <div className={styles.container}>
      <h3 className={styles.text}>File Upload with provided accept prop</h3>
      <pre>accept=['.png']</pre>
      <WppFileUpload
        value={file}
        onWppChange={handleFileUploadChange}
        data-testid="file-upload-multiple"
        size={1}
        accept={['.png']}
      />
    </div>
  )
}
