// examples/angular/src/app/pages/file-upload-example/examples/accept-prop/accept-prop.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'

@Component({
  selector: 'accept-prop-example',
  templateUrl: './accept-prop.html',
  styleUrls: ['./../../file-upload.page.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AcceptProp {
  public formatPNG = ['.png']
  public file = []

  handleFileUploadChange = (event: Event) => {
    this.file = (event as CustomEvent).detail.value
  }
}

// examples/react/src/pages/FileUpload/Examples/AcceptProp.tsx
import { WppFileUpload } from '@platform-ui-kit/components-library-react'
import { useState } from 'react'

import styles from '../FileUpload.module.scss'

export const AcceptProp = () => {
  const [file, setFiles] = useState([])
  const handleFileUploadChange = (event: CustomEvent) => {
    setFiles(event.detail.value)
  }

  return (
    <div className={styles.container}>
      <h3 className={styles.text}>File Upload with provided accept prop</h3>
      <pre>accept=['.png']</pre>
      <WppFileUpload
        value={file}
        onWppChange={handleFileUploadChange}
        data-testid="file-upload-multiple"
        size={1}
        accept={['.png']}
      />
    </div>
  )
}
