// examples/vue/src/views/examples/vc/TreeVCExample/TreeSingleWithNewCustomSearch.vue
<script setup lang="ts">
import { ref } from 'vue'

import { WppInput, WppTree } from '@platform-ui-kit/components-library-vue'

import { debounce } from 'lodash'

import { data } from './config'
import type { TreeType } from '@platform-ui-kit/components-library/dist/types/components/wpp-tree/types'

const searchConfig = {
  isMatchingSearch: (item: TreeType, search: string) => item.title.toLocaleLowerCase().includes(search.toLowerCase()),
}

const search = ref('')
const treeData = ref(data)

const handleTreeChange = (event: CustomEvent) => {
  console.log('handleTreeChange event :>> ', event.detail)

  treeData.value = event.detail.treeState
}

const handleSearch = (ev: CustomEvent) => {
  search.value = ev.detail.value || ''
}

// In order to prevent rendering issues on big data, use debounce for search handler
const debouncedHandleSearch = debounce(handleSearch, 400)
</script>

<template>
  <h3 class="title">
    Single tree with new custom search: tree-item's text should include search string (not case sensitive)
  </h3>

  <WppInput class="search" type="search" placeholder="Search" @wppChange="debouncedHandleSearch" />

  <WppTree
    class="tree"
    :data="treeData"
    :search="search"
    :searchConfig="searchConfig"
    @wppChange="handleTreeChange"
    data-testid="single-tree-custom-search"
  />
</template>

// examples/angular/src/app/pages/vc/trees/components/tree-single-with-new-custom-search/tree-single-with-new-custom-search.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { TreeActionClickEventDetail, TreeType } from '@platform-ui-kit/components-library'
import { data } from '../../config'
import { InputChangeEventDetail } from '@platform-ui-kit/components-library'

@Component({
  selector: 'app-single-tree-with-new-custom-search-example',
  templateUrl: './tree-single-with-new-custom-search.html',
  styleUrls: ['./tree-single-with-new-custom-search.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeSingleWithNewCustomSearch {
  public searchValue = ''
  public treeData = data

  public searchConfig = {
    isMatchingSearch: (item: TreeType, search: any) => item.title.toLocaleLowerCase().includes(search.toLowerCase()),
  }

  public handleSearch = (e: Event) => {
    this.searchValue = (e as CustomEvent<InputChangeEventDetail>).detail.value || ''
  }

  //TO DO: return back this logic in future
  // In order to prevent rendering issues on big data, use debounce for search handler
  // public debouncedHandleSearch = debounce(this.handleSearch, 400)

  public handleTreeChange = (event: Event) => {
    console.log('handleTreeChange event :>> ', (event as CustomEvent).detail)
    this.treeData = (event as CustomEvent).detail.treeState
  }

  public handleActionClick = (event: Event) => {
    console.log('handleActionClick', (event as CustomEvent<TreeActionClickEventDetail>).detail)
  }
}
