// examples/vue/src/views/examples/SelectsExample/Examples/CustomDropdown.vue
<script setup lang="ts">
import { WppInput, WppIconChevron, WppPopover, WppListItem } from '@platform-ui-kit/components-library-vue'

const OPTIONS_LIST = ['Admin', 'Country Admin', 'User']
import { ref } from 'vue'

const selectedOption = ref()
const isActive = ref<boolean>(false)
const popoverRef = ref<HTMLWppPopoverElement>()

const handleOptionSelect = (chosenOption: string) => {
  selectedOption.value = chosenOption
  popoverRef.value?.closePopover
}

const style: Record<string, string> = { '--wpp-list-item-width': '200px' }
</script>

<template>
  <WppPopover
    :ref='popoverRef'
    :config="{
    onShow: () => isActive = true,
    onHide: () => isActive = false,
    triggerElementWidth: true,
    }"
  >
    <WppInput
      :value='selectedOption'
      slot="trigger-element"
      placeholder="Select user role"
      :labelConfig="{ text: 'Role (Custom dropdown using WppInput + WppPoppover)' }"
      name="custom-input-name"
      required
    >
      <WppIconChevron slot="icon-end" :direction="isActive ? 'up' : 'down'" />
    </WppInput>
    <div :style='style'>
      <WppListItem
        v-for="option in OPTIONS_LIST"
        :key='option'
        :checked='selectedOption === option'
        @wppChangeListItem='handleOptionSelect(option)'
      >
        <p slot="label">{{ option }}</p>
      </WppListItem>
    </div>
  </WppPopover>
</template>

// examples/angular/src/app/pages/selects-example/Example/custom-dropdown.ts
import { ChangeDetectionStrategy, Component, ElementRef } from '@angular/core'
import { WppPopover } from '@platform-ui-kit/components-library-angular'

@Component({
  selector: 'app-custom-dropdown',
  templateUrl: './custom-dropdown.html',
  styleUrls: ['./custom-dropdown.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CustomDropdown {
  public OPTIONS_LIST = ['Admin', 'Country Admin', 'User']

  public selectedOption = ''
  public isActive = false
  public popoverRef!: ElementRef<WppPopover>
  public popoverConfig = {
    onShow: () => (this.isActive = true),
    onHide: () => (this.isActive = false),
    triggerElementWidth: true,
  }
  public labelConfig = { text: 'Role (Custom dropdown using WppInput + WppPoppover)' }

  public handleOptionSelect = (selectedOption: string) => {
    this.selectedOption = selectedOption
    this.popoverRef.nativeElement.closePopover()
  }

  public style: Record<string, string> = { '--wpp-list-item-width': '200px' }

  public handleIconState() {
    const state: string = this.isActive ? 'up' : 'down'

    return state
  }
}
