// examples/vue/src/views/examples/vc/TreeVCExample/TreeMultipleWithoutSearchHighlight.vue
<script setup lang="ts">
import { ref } from 'vue'
import { WppTree, WppInput } from '@platform-ui-kit/components-library-vue'

import { dataWithLongNames } from "./config";
import type { InputChangeEventDetail, TreeChangeEventDetail } from '@platform-ui-kit/components-library'
import { debounce } from "lodash";

const treeData = ref(dataWithLongNames)
const search = ref('')

const handleTreeChange = (event: CustomEvent<TreeChangeEventDetail>) => {
  treeData.value = event.detail.treeState
}

const handleSearch = (e: CustomEvent<InputChangeEventDetail>) => {
  search.value = e.detail.value || ''
}

// In order to prevent rendering issues on big data, use debounce for search handler
const debouncedHandleSearch = debounce(handleSearch, 400);
</script>

<template>
  <div>
    <h3 class="title">Multiple tree without search highlight</h3>
    <WppInput class="search" @wppChange="debouncedHandleSearch" type="search" placeholder="Search"/>
    <WppTree
      class="tree"
      :data="treeData"
      :search="search"
      multiple
      @wppChange="handleTreeChange"
      disableSearchHighlight
      data-testid="multiple-tree"
    />
  </div>
</template>

// examples/angular/src/app/pages/vc/trees/components/tree-multiple-without-search-highlight/tree-multiple-without-search-highlight.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { debounce } from 'lodash'
import { dataWithLongNames } from '../../config'
import { InputChangeEventDetail, TreeChangeEventDetail } from '@platform-ui-kit/components-library'

@Component({
  selector: 'app-multiple-tree-without-highlights-example',
  templateUrl: './tree-multiple-without-search-highlight.html',
  styleUrls: ['./tree-multiple-without-search-highlight.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeMultipleWithoutSearchHighlight {
  public treeData = dataWithLongNames
  public search = ''

  public handleTreeChange = (event: Event) => {
    this.treeData = (event as CustomEvent<TreeChangeEventDetail>).detail.treeState
  }

  public handleSearch = (e: Event) => {
    this.search = (e as CustomEvent<InputChangeEventDetail>).detail.value || ''
  }

  // In order to prevent rendering issues on big data, use debounce for search handler
  public debouncedHandleSearch = debounce(this.handleSearch, 400)
}
