// examples/angular/src/app/pages/vc/trees/components/tree-multiple/tree-multiple.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { dataWithLongNames } from '../../config'

@Component({
  selector: 'app-multiple-tree-example',
  templateUrl: './tree-multiple.html',
  styleUrls: ['./tree-multiple.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeMultiple {
  public treeData = dataWithLongNames

  public handleTreeChange = (event: Event) => {
    console.log('handleTreeChange event :>> ', (event as CustomEvent).detail)

    this.treeData = (event as CustomEvent).detail.treeState
  }

  public handleActionClick = (event: Event) => {
    console.log('handleActionClick', (event as CustomEvent).detail)
  }
}

// examples/vue/src/views/examples/vc/TreeVCExample/TreeMultiple.vue
<script setup lang="ts">
import { ref } from "vue";

import { WppTree } from "@platform-ui-kit/components-library-vue";

import { dataWithLongNames } from "./config";

const treeData = ref(dataWithLongNames);

const handleTreeChange = (event: CustomEvent) => {
  console.log("handleTreeChange event :>> ", event.detail);

  treeData.value = event.detail.treeState;
};

const handleActionClick = (event: CustomEvent) => {
  console.log("handleActionClick", event.detail);
};
</script>

<template>
  <h3 class="title">Multiple tree with selected by default</h3>

  <WppTree
    class="tree"
    :data="treeData"
    multiple
    @wppChange="handleTreeChange"
    @wppActionClick="handleActionClick"
    :defaultSelectedIds="['2-1', '1']"
    data-testid="multiple-tree"
  />
</template>
