// examples/angular/src/app/pages/vc/trees/components/tree-single-with-quotation-marks/tree-single-with-quotation-marks.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { TreeActionClickEventDetail } from '@platform-ui-kit/components-library'
import { data } from '../../config'
import { InputChangeEventDetail } from '@platform-ui-kit/components-library'

@Component({
  selector: 'app-single-tree-quotation-marks-example',
  templateUrl: './tree-single-with-quotation-marks.html',
  styleUrls: ['./tree-single-with-quotation-marks.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeSingleWithQuotationMarks {
  public searchValue = ''
  public treeData = data

  public multipleWordSearch = (title: string, multipleWord: string[]) =>
    multipleWord.find(element => element && title.includes(element)) !== undefined

  public exactMatchSearch = (title: string, exactMatchChunks: string[]) =>
    exactMatchChunks.find(element => element && title.includes(element)) !== undefined

  public searchConfig = {
    isMatchSearch: (title: any, search: any) => {
      const exactMatch: string[] = []
      const multipleWord: string[] = []
      const regx = /("(.*?)"|\S+)/g

      for (const match of search.matchAll(regx) as unknown as any) {
        match[2] ? exactMatch.push(match[2]) : multipleWord.push(match[1].toLowerCase())
      }
      const scTitle = title.toLowerCase()

      return this.exactMatchSearch(title, exactMatch) || this.multipleWordSearch(scTitle, multipleWord)
    },
    transformSearchQuery: (search: string) => search.replace(/"/g, ''),
  }

  public handleSearch = (e: Event) => {
    this.searchValue = (e as CustomEvent<InputChangeEventDetail>).detail.value || ''
  }

  //TO DO: return back this logic in future
  // In order to prevent rendering issues on big data, use debounce for search handler
  // public debouncedHandleSearch = debounce(this.handleSearch, 400)

  public handleTreeChange = (event: Event) => {
    console.log('handleTreeChange event :>> ', (event as CustomEvent).detail)
    this.treeData = (event as CustomEvent).detail.treeState
  }

  public handleActionClick = (event: Event) => {
    console.log('handleActionClick', (event as CustomEvent<TreeActionClickEventDetail>).detail)
  }
}

// examples/vue/src/views/examples/vc/TreeVCExample/TreeSingleWithQuotationMarks.vue
<script setup lang="ts">
import type { InputChangeEventDetail, TreeActionClickEventDetail } from '@platform-ui-kit/components-library'
import { debounce } from 'lodash'
import { ref } from 'vue'
import { data } from '@/views/examples/vc/TreeVCExample/config'
import { WppInput, WppTree } from '@platform-ui-kit/components-library-vue'

const search = ref('')
const treeData = ref(data)

const multipleWordSearch = (title: string, multipleWord: string[]) =>
  multipleWord.find(element => element && title.includes(element)) !== undefined

const exactMatchSearch = (title: string, exactMatchChunks: string[]) =>
  exactMatchChunks.find(element => element && title.includes(element)) !== undefined

const searchConfig = {
  isMatchSearch: (title: any, search: any) => {
    const exactMatch: string[] = []
    const multipleWord: string[] = []
    const regx = /("(.*?)"|\S+)/g

    for (const match of search.matchAll(regx) as unknown as any) {
      match[2] ? exactMatch.push(match[2]) : multipleWord.push(match[1].toLowerCase())
    }
    const scTitle = title.toLowerCase()

    return exactMatchSearch(title, exactMatch) || multipleWordSearch(scTitle, multipleWord)
  },
  transformSearchQuery: (search: any) => search.replace(/"/g, ''),
}

const handleSearch = (e: CustomEvent<InputChangeEventDetail>) => {
  search.value = e.detail.value || ''
}

const debouncedHandleSearch = debounce(handleSearch, 400)

const handleTreeChange = (event: CustomEvent) => {
  console.log('handleTreeChange event :>> ', event.detail)
  treeData.value = event.detail.treeState
}

const handleActionClick = (event: CustomEvent<TreeActionClickEventDetail>) => {
  console.log('handleActionClick', event.detail)
}
</script>

<template>
  <div :style="{ marginTop: '1px' }" data-testid="quotation-marks-tree-area">
    <h3 class="title">Single tree with search with quotation marks</h3>
    <WppInput class="search" @wppChange="debouncedHandleSearch" type="search" placeholder="Search"
              data-testid="quotation-marks-input"/>
    <WppTree
      class="tree"
      :data="treeData"
      @wppChange="handleTreeChange"
      data-testid="quotation-marks-tree"
      @wppActionClick="handleActionClick"
      :search="search"
      :searchConfig="searchConfig"
    />
  </div>
</template>
