// examples/angular/src/app/pages/vc/trees/components/tree-multiple-with-default-selected-ids/tree-multiple-with-default-selected-ids.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { data } from '../../config'
import { TreeChangeEventDetail } from '@platform-ui-kit/components-library'

@Component({
  selector: 'app-multiple-tree-with-default-selected-ids-example',
  templateUrl: './tree-multiple-with-default-selected-ids.html',
  styleUrls: ['./tree-multiple-with-default-selected-ids.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeMultipleWithDefaultSelectedIds {
  public treeData = data

  public handleTreeChange = (event: Event) => {
    this.treeData = (event as CustomEvent<TreeChangeEventDetail>).detail.treeState
  }
}

// examples/vue/src/views/examples/vc/TreeVCExample/TreeMultipleWithDefaultSelectedIds.vue
<script setup lang="ts">
import { ref } from 'vue'
import { WppTree } from '@platform-ui-kit/components-library-vue'
import { data } from './config'
import type { TreeChangeEventDetail } from '@platform-ui-kit/components-library'

const treeData = ref(data)

const handleTreeChange = (event: CustomEvent<TreeChangeEventDetail>) => {
  treeData.value = event.detail.treeState
}
</script>

<template>
  <div>
    <h3 class="title">Multiple tree with default selected ids ['0-1', '1']</h3>
    <WppTree
      class="tree"
      :data="treeData"
      :defaultSelectedIds="['0-1', '1']"
      multiple
      @wppChange="handleTreeChange"
      data-testid="multiple-tree"
    />
  </div>
</template>
