// examples/vue/src/views/examples/AutocompleteExample/examples/ServerSearch.vue
<script lang="ts">
import { defineComponent } from "vue";
import type { AutocompleteDefaultOption } from "@platform-ui-kit/components-library";

import {
  WppAutocomplete,
  WppListItem,
} from "@platform-ui-kit/components-library-vue";

import SelectedValues from "../SelectedValues.vue";

import type { MovieOption } from "../options";
import { movieOptions } from "../options";

export default defineComponent({
  name: "ServerSearch",
  components: {
    WppAutocomplete: WppAutocomplete,
    WppListItem: WppListItem,
    SelectedValues: SelectedValues,
  },
  data() {
    return {
      movieOptions: movieOptions,
      serverDataValue: [] as AutocompleteDefaultOption[],
      isGettingInitialMoviesValue: true,
      isSearchingMovies: false,
      movieSearchValue: "",
      movieSearchResult: [] as MovieOption[],
      timer: null,
    };
  },
  mounted() {
    setTimeout(() => {
      this.serverDataValue = [
        {
          id: "tt2948356",
          label: "Zootopia",
          year: 2016,
          rating: 8,
          unavailable: false,
        },
        {
          id: "tt0107290",
          label: "Jurassic Park",
          year: 1993,
          rating: 8.2,
          unavailable: false,
        },
        {
          id: "tt1074638",
          label: "Skyfall",
          year: 2012,
          rating: 7.8,
          unavailable: true,
        },
      ];
      this.isGettingInitialMoviesValue = false;
    }, 2000);
  },
  watch: {
    movieSearchValue(newSearchValue, oldSearchValue) {
      if (newSearchValue.trim() === oldSearchValue.trim()) {
        return;
      }

      const movieSearchValueTrimmed = newSearchValue.trim();

      this.isSearchingMovies = true;

      const timeout = 700 + Math.round(Math.random() * 1300);
      setTimeout(() => {
        this.movieSearchResult = movieOptions
          .filter((option) => {
            const searchValue = movieSearchValueTrimmed.toLocaleLowerCase();

            return (
              option.label.toLocaleLowerCase().includes(searchValue) ||
              String(option.year).includes(searchValue)
            );
          })
          .sort((a, b) =>
            a.label.toLocaleLowerCase() > b.label.toLocaleLowerCase() ? 1 : -1
          );
        this.isSearchingMovies = false;
      }, timeout);
    },
  },
  methods: {
    handleSearchValueChange(event: CustomEvent) {
      this.movieSearchValue = event.detail;
    },
    handleChange(event: CustomEvent) {
      this.serverDataValue = event.detail.value;
    },
    handlePillCloseClick(removedId: number) {
      this.serverDataValue = this.serverDataValue.filter(
        (i) => i.id !== removedId
      );
    },
  },
});
</script>

<template>
  <div class="item">
    <WppAutocomplete
      required
      :loading="isSearchingMovies"
      :disabled="isGettingInitialMoviesValue"
      name="server-data"
      :labelConfig="{
        text: `${
          isGettingInitialMoviesValue ? '(Loading initial values) ' : ''
        }Server search with lots of customization (max 5 selected items)`,
      }"
      placeholder="Select movies"
      :value="serverDataValue"
      @wppSearchValueChange="handleSearchValueChange"
      @wppChange="handleChange"
      limitSelectedItems="5"
      multiple
      showCreateNewElement
      simpleSearch
    >
      <WppListItem
        v-for="option in movieOptions"
        :key="option.id"
        :value="option"
        :label="option.label"
        :disabled="option.unavailable"
      >
        <p slot="label">
          <span class="unavailable" v-if="option.unavailable">(Sold out) </span>
          {{ option.label }} <span class="year">({{ option.year }})</span>&nbsp;
          <span class="rating">⭐ {{ option.rating.toFixed(1) }}</span>
        </p>
      </WppListItem>
      <SelectedValues
        :values="serverDataValue"
        @closeClick="(value) => handlePillCloseClick(value)"
      />
    </WppAutocomplete>
  </div>
</template>

<style scoped></style>

// examples/angular/src/app/pages/autocomplete-example/components/server-search/server-search.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { MovieOption, movieOptions } from '@platform-ui-kit/react-example/src/pages/Autocomplete/options'
import { AutocompleteDefaultOption } from '@platform-ui-kit/components-library'

@Component({
  selector: 'app-autocomplete-with-server-search-example',
  templateUrl: './server-search.html',
  styleUrls: ['./server-search.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ServerSearch {
  public serverDataValue: AutocompleteDefaultOption[] = []
  public isGettingInitialMoviesValue = true
  public isSearchingMovies = true
  public movieSearchValue = ''
  public movieSearchValueTrimmed = this.movieSearchValue.trim()
  public moviesLoadingNote = this.isGettingInitialMoviesValue ? '(Loading initial values) ' : ''
  public movieSearchResult: MovieOption[] = []
  public labelConfig = `${this.moviesLoadingNote}Server search with lots of customization (max 5 selected items)`

  // Load initial server value
  mounted() {
    setTimeout(() => {
      this.serverDataValue = [
        {
          id: 'tt2948356',
          label: 'Zootopia',
          year: 2016,
          rating: 8,
          unavailable: false,
        },
        {
          id: 'tt0107290',
          label: 'Jurassic Park',
          year: 1993,
          rating: 8.2,
          unavailable: false,
        },
        {
          id: 'tt1074638',
          label: 'Skyfall',
          year: 2012,
          rating: 7.8,
          unavailable: true,
        },
      ]
      this.isGettingInitialMoviesValue = false
    }, 2000)
  }

  // Load movie options based on search
  public handleMovieSearchValue(newSearchValue: string, oldSearchValue: string) {
    if (newSearchValue.trim() === oldSearchValue.trim()) {
      return
    }

    const movieSearchValueTrimmed = newSearchValue.trim()

    this.isSearchingMovies = true

    const timeout = 700 + Math.round(Math.random() * 1300)

    setTimeout(() => {
      this.movieSearchResult = movieOptions
        .filter(option => {
          const searchValue = movieSearchValueTrimmed.toLocaleLowerCase()

          return option.label.toLocaleLowerCase().includes(searchValue) || String(option.year).includes(searchValue)
        })
        .sort((a, b) => (a.label.toLocaleLowerCase() > b.label.toLocaleLowerCase() ? 1 : -1))
      this.isSearchingMovies = false
    }, timeout)
  }

  public getLabelConfig = (text: string) => ({
    text,
  })

  public handleSearchValueChange(event: Event) {
    this.movieSearchValue = (event as CustomEvent).detail
  }

  public handleServerDataValueChange(event: Event) {
    this.serverDataValue = (event as CustomEvent).detail.value as any
  }
}
