// examples/react/src/pages/Autocomplete/SelectedValues.tsx
import { WppPill } from '@platform-ui-kit/components-library-react'
import { AutocompleteDefaultOption } from '@platform-ui-kit/components-library'

import styles from './Autocomplete.module.scss'
import React from 'react'

interface SelectedValuesComponent {
  values: AutocompleteDefaultOption[]
  onCloseClick: (a: number | string) => void
}

export const SelectedValues = ({ values, onCloseClick }: SelectedValuesComponent) => (
  <div slot="selected-values">
    {values.map(value => (
      <WppPill
        label={value.label}
        removable
        value={value.id}
        onWppClose={() => onCloseClick(value.id)}
        type="display"
        className={styles.pill}
        key={value.id}
      >
        {value.label}
      </WppPill>
    ))}
  </div>
)

// examples/vue/src/views/examples/AutocompleteExample/SelectedValues.vue
<script lang="ts">
import { defineComponent } from "vue";

import { WppPill } from "@platform-ui-kit/components-library-vue";

export default defineComponent({
  name: "SelectedValues",
  components: {
    WppPill: WppPill,
  },
  props: ["values"],
  methods: {
    handleCloseClick(value: number) {
      this.$emit("closeClick", value);
    },
  },
});
</script>

<template>
  <div slot="selected-values">
    <WppPill
      v-for="value in values"
      :key="JSON.stringify(value)"
      :label="value.label"
      removable
      :value="value.id"
      type="display"
      class="pill"
      @wppClose="() => handleCloseClick(value.id)"
    >
      {{ value.label }}
    </WppPill>
  </div>
</template>

<style scoped></style>
