// examples/vue/src/views/examples/vc/TreeVCExample/TreeSkeletonLoading.vue
<script setup lang="ts">
import { ref } from 'vue'

import { WppButton, WppTree } from '@platform-ui-kit/components-library-vue'

import { data } from './config'

const treeData = ref(data)
const loading = ref(true)

const handleTreeChange = (event: CustomEvent) => {
  console.log('handleTreeChange event :>> ', event.detail)

  treeData.value = event.detail.treeState
}

const toggleLoading = () => {
  loading.value = !loading.value
}
</script>

<template>
  <div data-testid="single-tree-container">
    <h3 class="title">Skeleton Loading tree</h3>
    <WppTree
      class="tree"
      :data="treeData"
      @wppChange="handleTreeChange"
      @wppActionClick="handleActionClick"
      data-testid="single-tree"
      skeleton-number-items="3"
      :loading="loading"
    />

    <WppButton @click="toggleLoading">Toggle loading</WppButton>
  </div>
</template>

<style lang="scss">
.wpp-button {
  margin-top: 40px;
}
</style>

// examples/angular/src/app/pages/vc/trees/components/tree-skeleton-loading/tree-skeleton-loading.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { data } from '../../config'

@Component({
  selector: 'app-skeleton-loading-tree-example',
  templateUrl: './tree-skeleton-loading.html',
  styleUrls: ['./tree-skeleton-loading.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeSkeletonLoading {
  public treeData = data
  public loading = true

  public handleTreeChange = (event: Event) => {
    console.log('handleTreeChange event :>> ', (event as CustomEvent).detail)

    this.treeData = (event as CustomEvent).detail.treeState
  }

  public handleActionClick = (event: Event) => {
    console.log('handleActionClick', (event as CustomEvent).detail)
  }

  public toggleLoading = () => {
    this.loading = !this.loading
  }
}
